apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx
  namespace: blue-green  # Specify your namespace
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: nginx
      previewService: nginx-preview
      autoPromotionEnabled: true
      steps:
        - setWeight: 50
        - pause: { duration: 10 }
        - setWeight: 100
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
