apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: blue-green
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-preview
  namespace: blue-green
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-preview
  type: ClusterIP
